### ISSUE TITLE
Issue with latest version of .NET core

### ISSUE THREAD

**Issue by joel-ld** [jusbuc2k/Justin.AspNetCore.LdapAuthentication#10]
Hello, 

Is it possible that the library don't work with the latest version of ASP.NET CORE /IDENTITY 2.2? 
I can't reach my AD domain....

Thanks.

**Comment by joel-ld** [comment]
@jusbuc2k  Any updates ?

**Comment by jusbuc2k** [comment]
@joel-ld sorry, I missed this issue. I've not compiled this for .NET 2.1 or 2.2 or used it with Identity 2.2, but I wouldn't expect not being able to reach the domain would be related to that. Can you post sample code with an error message or screenshots showing the problem?

**Comment by jusbuc2k** [comment]
@joel-ld I just compiled and ran an example MVC app against netcoreapp 2.2 with identity 2.2, and it all seems to be working. See my branch and example MVC app here:
https://github.com/jusbuc2k/Justin.AspNetCore.LdapAuthentication/tree/feature/aspnetidentity22
