### ISSUE TITLE
Issue with ASP.NET Core 2.0.0

### ISSUE THREAD

**Issue by joellacas** [jusbuc2k/Justin.AspNetCore.LdapAuthentication#2]
Since this morning, I migrate my application from .NET Core 1.1 to .NET Core 2.0.0 and I get an error message from your library.

Thank you in advance....
```
An error occurred while starting the application.
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Identity.UserManager`1' from assembly 'Microsoft.AspNetCore.Identity, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
RhWeb.Startup.ConfigureServices(IServiceCollection services)
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Identity.UserManager`1' from assembly 'Microsoft.AspNetCore.Identity, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
RhWeb.Startup.ConfigureServices(IServiceCollection services)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by jusbuc2k** [comment]
@joellacas, I'll try and do a 2.0 upgrade on this library tonight and see what happens. I haven't tried it with 2.0 yet, sorry. I'll report back my findings as soon as I can.

**Comment by joellacas** [comment]
@jusbuc2k 
Thanks for the fast answer :) My app needs to be deployed in couple weeks and this feature is the best solution for us !

**Comment by jusbuc2k** [comment]
@joellacas Hopefully it's something simple I can help you with. I was hoping System.DirectoryServices would make it into the 2.0 release, but it looks like it's still scheduled for 2.1 here: https://github.com/dotnet/corefx/issues/2089

**Comment by joellacas** [comment]
@jusbuc2k  Sounds good. So you will able to port your library to .NET Core 2.0 ?

**Comment by joellacas** [comment]
@jusbuc2k Any update ?

**Comment by jusbuc2k** [comment]
@joellacas, sorry I didn't get to it this weekend. I'm going to work on it now. I'll report back in bit.

**Comment by jusbuc2k** [comment]
@joellacas, I just pushed a preview00 version to nuget.org supporting asp.net identity 2.0 / netstandard 2.0. Try it out and report back. I tested it with a File->New Project, ASP.NET Core website in VS 2017 and it worked.

https://www.nuget.org/packages/Justin.AspNetCore.LdapAuthentication/2.0.0-preview00

**Comment by joellacas** [comment]
@jusbuc2k  Awesome! It's work again. Thank you for your help :)

**Comment by jusbuc2k** [comment]
@joellacas Good to hear!
