### ISSUE TITLE
How can I registry w/o a password?

### ISSUE THREAD

**Issue by HowardPWardinkle** [jusbuc2k/Justin.AspNetCore.LdapAuthentication#5]
I created a Core 2.0 app with the template using Identity and hooked in LdapAuthentication.  It works great, but registration requires a password, otherwise I get an error saying it's too short.  I'm just coming up to speed on ASP.NET Core 2 and figure they're some trick.  

In the Register.cshtml.cs I changed UserManager to LdapUserManager and in LdapUserManager I tried overriding SupportsUserPassword to return false always.  

Any help is appreciated.

**Comment by jusbuc2k** [comment]
You have to modify the registration experience in some way to accomplish this. Presumably you don't want the app to create a new AD user, so if that's the case, you might want to validate their AD password as part of the registration process, or possibly eliminate the registration process altogether. This project doesn't implement a full LDAP user store which would be required to accomplish the later.

**Comment by HowardPWardinkle** [comment]
Thanks.  I found to prevent Identity from validating the password, I created a NoPasswordHasher and then in the controller's constructor that gets an injected LdapUserManager I set the hasher and clear validators.  If you're interested I can update the readme to give directions on modifying the code from the template to use your package.

```csharp
	_ldapUserManager.PasswordHasher = new NoPasswordHasher<ApplicationUser>();
	_ldapUserManager.PasswordValidators.Clear();
```

**Comment by jusbuc2k** [comment]
@JimWatV1 sorry I was out of the loop for a bit. If you want to suggest some readme changes go ahead.
