### ISSUE TITLE
Login Failed LDAP credentials

### ISSUE THREAD

**Issue by elmago1996** [jusbuc2k/Justin.AspNetCore.LdapAuthentication#6]
Hello Justin, Yesterday I wanted to try authenticating my asp.net core 1.x application by LDAP and followed the steps you indicated in the github and the result of PasswordSignInAsync returns false I wanted to know if you could help me with this topic I just started to investigate and I do not know much about LDAP, yesterday I found an LDAP test host (https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/) that I am trying to connect to I wait for your answer and your prompt help thanks

**Comment by jusbuc2k** [comment]
@elmago1996, sorry I was out of the loop for a bit. Did you eventually solve your problem? If you have some specific code examples or scenarios that you suspect are an issue with the library, please feel free to post them and re-open the issue. Thanks.
