### ISSUE TITLE
active directory user data

### ISSUE THREAD

**Issue by hgmauri** [jusbuc2k/Justin.AspNetCore.LdapAuthentication#7]
Good morning, Justin.
Can you tell me if it is possible to bring an object with the active directory user data with the Novell.Directory.Ldap dll?

**Comment by jusbuc2k** [comment]
@hgmauri, Are you referring to accessing AD attributes over LDAP with the Novel library?  If so, I'm sure you can do it, but it is not in the scope of this library. I would post a question over on their issues page.
