### ISSUE TITLE
Issue with ASP.NET Core 2.1

### ISSUE THREAD

**Issue by klaus-liebler** [jusbuc2k/Justin.AspNetCore.LdapAuthentication#8]
Hi Justin,
when playing around with .net core 2.1, I get an exception on startup
"An error occurred while starting the application.
InvalidOperationException: Scheme already exists: Identity.Application"

Steps to reproduce

- In VisualStudio 15.7.5, create a new asp.net core web applcation based on ASP.NET 2.1 (2.1.302 is installed) with „individual“ user accounts.
- Install-Package -Pre Justin.AspNetCore.LdapAuthentication
- Update the appsettings.json with the LdapAuth snippet
- Replace the „AddDefaultIdentity“ call in ConfigureServices with your „AddIdentity<ApplicationUser, IdentityRole>()“
- As the Type „ApplicationUser“ does not exist in the template, create a empty new „public class ApplicationUser:IdentityUser“.
- Run the application

**Comment by jusbuc2k** [comment]
Klaus, sorry I took so long to get back to you on this, is this still an issue? I'll try your steps later today if I have time.

**Comment by klaus-liebler** [comment]
In the meanwhile, I dived deeper into the authentication infrastructure of asp.net core and created my very own LDAP-A&A implementation (unfortunately closed source...). So, for me, this is not an issue any more, but maybe for others?

Regards, Klaus
